// Copyright (C) 2009

package net.continuumsecurity.captcha.caption;

/**
 * Represents error generated by server while processing CAPTCHA 
 * @author 
 *
 */
public class CaptchaSolveException extends Exception {
	private static final long serialVersionUID = 1L;
	private final int _errorNum;
    private final String _errorMessage;
    private final String _serverSoftwareVersion;
    
    /**
     * Constructor
     * @param errorNum Error number
     * @param message Error message
     * @param serverSoftwareVersion Version of the software on the server
     */
    public CaptchaSolveException(int errorNum, String message, String serverSoftwareVersion) {
    	super(String.format("Error %d/%s: %s", errorNum, serverSoftwareVersion, message));
    	_errorNum = errorNum;
    	_errorMessage = message;
    	_serverSoftwareVersion = serverSoftwareVersion;
	}
    
    /**
     * Error number
     * @return Error number
     */
	public int getErrorNum() {
		return _errorNum;
	}
	
	/**
	 * Error message 
	 * @return Error message 
	 */
	public String getErrorMessage() {
		return _errorMessage;
	}
	
	/**
	 * Version of the software on the server
	 * @return Version of the software on the server
	 */
	public String getServerSoftwareVersion() {
		return _serverSoftwareVersion;
	}
}
