// Copyright (C) 2009

package net.continuumsecurity.captcha.caption;

/**
 * Represents result of CAPTCHA solve 
 * @author 
 *
 */
public class SolveResult {
	private final String _result;
	private final String _serverSoftwareVersion;
	private final String _captchaId;

	/**
	 * Constuctor
	 * @param result String CAPTCHA
	 * @param serverSoftwareVersion Version of the software on the server
	 * @param captchaId ID of the CAPTCHA generated by the server
	 */
	SolveResult(String result, String serverSoftwareVersion, String captchaId) {
		_result = result;
		_serverSoftwareVersion = serverSoftwareVersion;
		_captchaId = captchaId;
	}
	
	/**
	 * String CAPTCHA
	 * @return String CAPTCHA
	 */
	public String getResult() {
		return _result;
	}
	
	/**
	 * Version of the software on the server
	 * @return Version of the software on the server
	 */
	public String getServerSoftwareVersion() {
		return _serverSoftwareVersion;
	}
	
	/**
	 * ID of the CAPTCHA generated by the server
	 * @return ID of the CAPTCHA generated by the server
	 */
	public String getCaptchaId() {
		return _captchaId;
	}
}
